# permissions for end users to edit observers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observer-editor-role
rules:
- apiGroups:
  - internal.automatedmonkey.life
  resources:
  - observers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - internal.automatedmonkey.life
  resources:
  - observers/status
  verbs:
  - get
